const projects = [
  {
    id: 1,
    url: "portfolio",
    img: "/projects/portfolio/thumb.png",
    title: "Portfolio",
    type: "Website",
    icon: "/projects/portfolio/home.webp",
    github: "https://github.com/DigvijayInacio/Portfolio",
    web: "https://Digvijay.vercel.app/",
    description:
      "This portfoli website which give more information about me . .",
    tags: [
      { name: "Next JS", icon: "/skills/next-js.svg" },
      { name: "TypeScript", icon: "/skills/typescript.svg" },
      { name: "Styled Components", icon: "/skills/styled-components.svg" },
    ],
    print: [
      { name: "Thumb", img: "/projects/portfolio/thumb.png" },
      { name: "About", img: "/projects/portfolio/about.png" },
      { name: "Skills", img: "/projects/portfolio/skills.png" },
      { name: "Projects", img: "/projects/portfolio/projects.png" },
      { name: "Contact", img: "/projects/portfolio/contact.png" },
      { name: "Detail-1", img: "/projects/portfolio/detail-1.png" },
      { name: "Detail-2", img: "/projects/portfolio/detail-2.png" },
      { name: "Detail-3", img: "/projects/portfolio/detail-3.png" },
      { name: "Detail-4", img: "/projects/portfolio/detail-4.png" },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
  {
    id: 2,
    url: "turtle-movie",
    img: "/projects/turtlemovie/turtle.png",
    title: "Turtle Movie",
    type: "Website",
    icon: "https://imgur.com/f0pqZyp.png",
    github: "https://github.com/DigvijayInacio/Turtle-Movie",
    web: "https://turtle-movie.vercel.app/",
    description: "this is turtle movie and hollywood movie",
    tags: [
      { name: "React Js", icon: "/skills/react.svg" },
      { name: "React Router", icon: "/skills/code.svg" },
      { name: "TypeScript", icon: "/skills/typescript.svg" },
      { name: "Styled Components", icon: "/skills/styled-components.svg" },
    ],
    print: [
      { name: "Movie", img: "/projects/turtlemovie/turtle-movie.png" },
      { name: "Movie-Popular", img: "/projects/turtlemovie/movie-popular.png" },
      {
        name: "Series-Popular",
        img: "/projects/turtlemovie/series-popular.png",
      },
      { name: "Detail", img: "/projects/turtlemovie/detail-home.png" },
      { name: "Detail-elenco", img: "/projects/turtlemovie/detail-elenco.png" },
      { name: "Detail-video", img: "/projects/turtlemovie/detail-video.png" },
      { name: "Peoples", img: "/projects/turtlemovie/peoples.png" },
      { name: "Detail-people", img: "/projects/turtlemovie/detail-people.png" },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
  {
    id: 3,
    url: "playstation",
    img: "/projects/playstation/playstation.webp",
    title: "PlayStation",
    type: "Website",
    icon: "/projects/playstation/icon.svg",
    github: "https://github.com/DigvijayInacio/PlayStation",
    web: "https://playstation-4.vercel.app/",
    description: "this is e-commerce movie.",
    tags: [
      { name: "Html", icon: "/skills/html.svg" },
      { name: "Css", icon: "/skills/css.svg" },
      { name: "JavaScript", icon: "/skills/javascript.svg" },
    ],
    print: [
      { name: "Home", img: "/projects/playstation/playstation-home.png" },
      { name: "Home-2", img: "/projects/playstation/playstation-home-2.png" },
      { name: "About", img: "/projects/playstation/playstation-about.png" },
      { name: "Product", img: "/projects/playstation/playstation-product.png" },
      {
        name: "Product-2",
        img: "/projects/playstation/playstation-product-2.png",
      },
      { name: "Buy", img: "/projects/playstation/playstation-buy.png" },
      { name: "Contact", img: "/projects/playstation/playstation-contact.png" },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
  {
    id: 4,
    url: "podcast",
    img: "/projects/podcastr/podcastr-home.png",
    title: "Podcastr",
    type: "Website",
    icon: "/projects/podcastr/icon.svg",
    github: "https://github.com/DigvijayInacio/Podcastr",
    web: "https://podcastr-Digvijay.vercel.app/",
    description: "podcast movie",
    tags: [
      { name: "React JS", icon: "/skills/react.svg" },
      { name: "TypeScript", icon: "/skills/typescript.svg" },
      { name: "Next JS", icon: "/skills/next-js.svg" },
      { name: "Sass", icon: "/skills/sass.svg" },
    ],
    print: [
      { name: "Home", img: "/projects/podcastr/podcastr-home.png" },
      { name: "Home-2", img: "/projects/podcastr/podcastr-home-2.png" },
      { name: "Detail", img: "/projects/podcastr/podcastr-detail.png" },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
  {
    id: 5,
    url: "ds-meta",
    img: "/projects/dsmeta/dsmeta.png",
    title: "DS Meta",
    type: "Website",
    icon: "/projects/dsmeta/dsmeta-icon.svg",
    github: "https://github.com/DigvijayInacio/DsMeta",
    web: "https://dsmeta-Digvijay.netlify.app/",
    description: "ds-meta tutorial and its movie based hollywood.",
    tags: [
      { name: "Java", icon: "/skills/java.svg" },
      { name: "Spring", icon: "/skills/spring.svg" },
      { name: "TypeScript", icon: "/skills/typescript.svg" },
      { name: "React Js", icon: "/skills/react.svg" },
      { name: "Axios", icon: "/skills/code.svg" },
      { name: "API Rest", icon: "/skills/code.svg" },
      { name: "H2 Database", icon: "/skills/database.svg" },
    ],
    print: [
      { name: "Home", img: "/projects/dsmeta/dsmeta.png" },
      { name: "Footer", img: "/projects/dsmeta/dsmeta-footer.png" },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
  {
    id: 6,
    url: "github-blog",
    img: "/projects/github-blog/github-blog-home.png",
    title: "Github Blog",
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
    github: "https://github.com/Digvijay/Github-Blog",
    web: "https://github-blog-Digvijay.vercel.app/",
    description: "github hub clone projects.",
    tags: [
      { name: "Next JS", icon: "/skills/next-js.svg" },
      { name: "TypeScript", icon: "/skills/typescript.svg" },
      { name: "Stitches", icon: "/skills/code.svg" },
    ],
    print: [
      { name: "Home", img: "/projects/github-blog/github-blog-home.png" },
      { name: "Home-2", img: "/projects/github-blog/github-blog-home-2.png" },
      { name: "Detail", img: "/projects/github-blog/github-blog-detail.png" },
      {
        name: "Detail-2",
        img: "/projects/github-blog/github-blog-detail-2.png",
      },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
  {
    id: 6,
    url: "whatsapp",
    img: "/projects/whatsapp/login.png",
    title: "WhatsApp",
    type: "Website",
    icon: "/projects/whatsapp/icon.svg",
    github: "https://github.com/DigvijayInacio/WhatsApp",
    web: "https://whatsapp-green.vercel.app/",
    description: "whatsapp clone project.",
    tags: [
      { name: "React JS", icon: "/skills/react.svg" },
      { name: "Styled Components", icon: "/skills/styled-components.svg" },
      { name: "Firebase", icon: "/skills/firebase.svg" },
    ],
    print: [
      { name: "Login", img: "/projects/whatsapp/login.png" },
      { name: "Home-light", img: "/projects/whatsapp/home-light.png" },
      { name: "Home-dark", img: "/projects/whatsapp/home-dark.png" },
      { name: "Chat", img: "/projects/whatsapp/chat.png" },
      { name: "Chat-emoji", img: "/projects/whatsapp/chat-emoji.png" },
      { name: "New-chat", img: "/projects/whatsapp/new-chat.png" },
    ],
    video: "https://www.youtube.com/watch?v=RGKi6LSPDLU",
  },
];

export default projects;
